### ISSUE TITLE
请问多用户改怎么配置。

### ISSUE THREAD

**Issue by HankMo** [moeshin/cx-auto-sign#10]
我登录多个用户 但是开始签到就是AppConfig.json5里面 "DefaultUsername": "", // 默认用户，这里登录的账号，比如Configs 里面有3个用户，他就会以默认用户签到三次。其他的不签到

**Comment by moeshin** [comment]
```
dotnet ./cx-auto-sign.dll work -u 用户
```

**Comment by HankMo** [comment]
这样还是一个用户签到呀

**Comment by HankMo** [comment]
![image](https://user-images.githubusercontent.com/60347960/161557149-2d3a4f81-ef80-443d-b04c-acad1fa3be53.png)
我给每一个用户下面都配置了这样也不行 还是光默认用户签到

**Comment by moeshin** [comment]
> ```
> dotnet ./cx-auto-sign.dll work -u 用户
> ```

这样是只有一个用户运行，你多运行几个

**Comment by HankMo** [comment]
多开几个运行窗口？

**Comment by HankMo** [comment]
![image](https://user-images.githubusercontent.com/60347960/161560794-83eeab52-1a0a-496d-8c40-0124a64a92b2.png) 
像这样多开吗？

**Comment by moeshin** [comment]
差不多 :joy:

**Comment by moeshin** [comment]
每个都跑不一样的用户

```
dotnet ./cx-auto-sign.dll work -u 用户1
dotnet ./cx-auto-sign.dll work -u 用户2
dotnet ./cx-auto-sign.dll work -u 用户3

...
```

**Comment by HankMo** [comment]
好了好了 ，谢谢 。帮了大忙了。问一下这个应该比那种api每隔多长时间请求一下的 要不容易被检测异常吧

**Comment by moeshin** [comment]
我也不清楚啊哈哈 :joy:

**Comment by HankMo** [comment]
😂好吧 ，谢谢了

**Comment by Epxir** [comment]
./start.sh -a

**Comment by HankMo** [comment]
> ./start.sh -a

啥意思
![image](https://user-images.githubusercontent.com/60347960/161894322-eecfbd0d-1f75-4217-9a7a-029918a090f4.png)
没效果呀

**Comment by moeshin** [comment]
> > ./start.sh -a
> 
> 啥意思 ![image](https://user-images.githubusercontent.com/60347960/161894322-eecfbd0d-1f75-4217-9a7a-029918a090f4.png) 没效果呀

这个不是给 Windows 用的
