### ISSUE TITLE
start.sh 多次后进程数虽然为一，但是pushplus会多次推送！

### ISSUE THREAD

**Issue by Epxir** [moeshin/cx-auto-sign#11]
另外希望新加功能
按星期几或时间使用Images（同一门课有多个教室）、推送分用户
感谢作者一直更新！

**Comment by HankMo** [comment]
我也遇到多个用户同时挂这 然后有一个用户会多次签到，然后多次推送。但是我帮那个用户关了 重新挂又好了

**Comment by Epxir** [comment]
restart也会多次推送

**Comment by moeshin** [comment]
推送分用户是可以的，在用户配置里设置
![image](https://user-images.githubusercontent.com/28248888/161955212-690bcffc-8718-4615-8162-9254682bcb8b.png)

**Comment by moeshin** [comment]
[v2.1.4](https://github.com/moeshin/cx-auto-sign/releases/tag/v2.1.4)
