### ISSUE TITLE
在使用start.sh的时候出现两个进程，疑似BUG

### ISSUE THREAD

**Issue by BingZi-233** [moeshin/cx-auto-sign#14]
![示意图](https://s1.ax1x.com/2022/04/17/LanU10.png)

**Comment by moeshin** [comment]
单次 start -a 吗，遍历配置文件夹的，应该不会有问题吧。
这个是什么视图，我研究研究。

**Comment by moeshin** [comment]
https://github.com/moeshin/cx-auto-sign/blob/83ef0df00d69812728e96aab77ed712c0916b189/scripts/start.sh#L22
https://github.com/moeshin/cx-auto-sign/blob/83ef0df00d69812728e96aab77ed712c0916b189/scripts/.base.sh#L49-L52

**Comment by BingZi-233** [comment]
根据使用情况来看，有时候会启动两个。然后重启、关闭都只会关闭一个。导致出现了一个不受管控的进程

**Comment by moeshin** [comment]
有可能是文件锁的问题，好像不会马上生效，我才加了延迟

**Comment by BingZi-233** [comment]
可能是我比较着急，然后看到有多余的就kill掉了

**Comment by BingZi-233** [comment]
你可以通过htop命令看到这个视图，按F4进行过滤 使用dotnet就能过滤出来。如果可以，建议直接KILL掉里面的那个白色的dotnet命令，这样可以直接结束。不会出现孤儿进程
