### ISSUE TITLE
这咋解决

### ISSUE THREAD

**Issue by iamxiaodeng** [moeshin/cx-auto-sign#22]
<img width="720" alt="微信图片_20220505094847" src="https://user-images.githubusercontent.com/104954347/166853105-bdbc59ba-d1a1-4584-a6ce-c043b1939bdc.png">

**Comment by moeshin** [comment]
> ### 0x00 运行环境
> 
> 首先需要在 [.Net Runtime 下载页](https://dotnet.microsoft.com/download/dotnet/current/runtime) 下载并安装 **.NET5 Runtime**（提示：Run server apps下边的下载）。
