### ISSUE TITLE
powershell运行时报错

### ISSUE THREAD

**Issue by 2861318717** [moeshin/cx-auto-sign#23]
>> dotnet ./cx-auto-sign.dll init -u "user" -p "pwd"
无法执行，因为找不到指定的命令或文件。
可能的原因包括:
  *内置的 dotnet 命令拼写错误。
  *你打算执行 .NET 程序，但 dotnet-./cx-auto-sign.dll 不存在。
  *你打算运行全局工具，但在路径上找不到具有此名称且前缀为 dotnet 的可执行文件。
执行的时候会出现这样的问题,文件夹中是cx-auto-sign.sln,可是尝试更改后缀执行也是报错,不太明白,请求指点一下

**Comment by moeshin** [comment]
首先你命令打错了吧，其次你下的是源码吧？

> 0x00 运行环境
> 首先需要在 [.Net Runtime 下载页](https://dotnet.microsoft.com/download/dotnet/current/runtime) 下载并安装 .NET5 Runtime（提示：Run server apps下边的下载）。
> 
> 然后在 [Release页面](https://github.com/moeshin/cx-auto-sign/releases) 下载 cx-auto-sign.zip，并解压到某个目录。
> 
>（你也可以在 [Actions](https://github.com/moeshin/cx-auto-sign/actions) 中找到自动编译的测试版）
