### ISSUE TITLE
支持更多推送渠道

### ISSUE THREAD

**Issue by ghost** [moeshin/cx-auto-sign#27]
“因公司业务调整，pushplus将于2022年5月31日暂停服务。”
如果可能，加个Bark?  (https://github.com/Finb/Bark) 感激不尽
`https://api.day.app/{token}/{text}`

**Comment by moeshin** [comment]
我记得好像有两个 PushPlus，我用的是 https://www.pushplus.plus/ 这个没有提示

**Comment by moeshin** [comment]
Bark 这个是跨平台吗，还是只有 iOS？

**Comment by ghost** [comment]
噗。居然还有一个pushplus 我去看看！Bark应该是只有iOS，Android似乎没见过类似的工具

**Comment by moeshin** [comment]
配置 `BarkUrl`，例如：`https://api.day.app/yourkey`
