### ISSUE TITLE
签到接口失效

### ISSUE THREAD

**Issue by moeshin** [moeshin/cx-auto-sign#28]

**Comment by moeshin** [comment]
备用方案

<details>

## Web 接口
普通、手势、签到码
`https://mobilelearn.chaoxing.com/v2/apis/sign/signIn?activeId=`

**Comment by moeshin** [comment]
现在由 404 变为非法请求，在签到前访问一次 preSign 即可

**Comment by BingZi-233** [comment]
该问题已被修复对吧，只需要使用最新的版本即可？

**Comment by moeshin** [comment]
> 该问题已被修复对吧，只需要使用最新的版本即可？

是的
