### ISSUE TITLE
登陆账号时报错，腾讯云centOS7.6环境

### ISSUE THREAD

**Issue by DangerFickle** [moeshin/cx-auto-sign#29]
![image](https://user-images.githubusercontent.com/59493932/171026797-baae7d6f-74c8-47f5-96c5-e6711ee9817a.png)

**Comment by moeshin** [comment]
过段时间看看，不行的话这个版本看看 https://github.com/moeshin/cx-auto-sign/actions/runs/2413827707

**Comment by moeshin** [comment]
或者可能是证书问题
https://www.cnblogs.com/devdog/p/13919868.html
https://stackoverflow.com/questions/40243156/restsharp-returns-status-0-while-calling-post-method

**Comment by DangerFickle** [comment]
从7.6重装到8.2。正常运行

**Comment by moeshin** [comment]
那可能是证书问题了
