### ISSUE TITLE
莫名其妙停止运行！

### ISSUE THREAD

**Issue by Epxir** [moeshin/cx-auto-sign#3]
![截屏2021-12-03 下午2 32 07](https://user-images.githubusercontent.com/79371047/144556391-682531f9-4cf9-43c1-8063-aeff13a9a66d.png)
挂服务器上后，过段时间会停止运行

**Comment by moeshin** [comment]
07:47:44 之后就没有日志了吗，程序还在运行吗

**Comment by Epxir** [comment]
> 07:47:44 之后就没有日志了吗，程序还在运行吗

怎么检测是否运行？这个时间戳后不会刷新出日志了，感觉是不运行

**Comment by moeshin** [comment]
ssh 直接执行命令吗，还是 nohup。ssh 可能会是配置问题断开连接

**Comment by Epxir** [comment]
> ssh 直接执行命令吗，还是 nohup。ssh 可能会是配置问题断开连接

ssh 挂 screen 上了，回来看有时会这样。日志不刷新就不会再刷了

**Comment by moeshin** [comment]
https://github.com/moeshin/cx-auto-sign/releases/tag/v2.1.1
这版本康康
