### ISSUE TITLE
大佬，我可以请教一下学习通IM获取签到的原理和大概过程吗

### ISSUE THREAD

**Issue by LeonardoNorskog** [moeshin/cx-auto-sign#31]
大佬，我可以请教一下学习通IM获取签到的原理和大概过程嘛，只会一点py，看不懂大佬写的源码

**Comment by moeshin** [comment]
https://uint128.com/2020/11/16/%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9AIM%E5%8D%8F%E8%AE%AE%E5%88%86%E6%9E%90/
