### ISSUE TITLE
关于TG推送自建API的选择

### ISSUE THREAD

**Issue by 409-conflict** [moeshin/cx-auto-sign#35]
可否在配置文件中添加自选TGAPI，或者允许直接填入完整api取代原本推送链接（例如：https://tg.push.com/bot:123.....）

**Comment by moeshin** [comment]
这咋还有得自选:joy:

接口后面的 `/sendMessage` 和请求内容和原来都是一样的是吧？

https://github.com/moeshin/cx-auto-sign/blob/67558f8ad3a1fff218f67c90505e2129d0210e6e/cx-auto-sign/Notification.cs#L248-L264

**Comment by moeshin** [comment]
就酱吧？

```json
{
  "TelegramBotToken": "https://tg.push.com/bot:123..."
}
```

**Comment by 409-conflict** [comment]
> 就酱吧？
> 
> ```json
> {
>   "TelegramBotToken": "https://tg.push.com/bot:123..."
> }
> ```

是的

---

> 这咋还有得自选😂
> 
> 接口后面的 `/sendMessage` 和请求内容和原来都是一样的是吧？
> 
> https://github.com/moeshin/cx-auto-sign/blob/67558f8ad3a1fff218f67c90505e2129d0210e6e/cx-auto-sign/Notification.cs#L248-L264

抱歉是我表述不明确，TG对于国内机器除了代理以外，最简单的途径就是反代API，昨天没说清楚这点，十分感谢

**Comment by 409-conflict** [comment]
QYWXtokenurl = 'https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={}&corpsecret={}'
QYWXposturl ='https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token={}'
    tokenurl=QYWXtokenurl.format(`企业微信的企业ID`,`企业微信的企业密钥`)
    getr = requests.get(tokenurl)
    access_token = getr.json().get('access_token')
    tmptext = "<div class=\"gray\">" + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + "</div> <div class=\"normal\">" + `小标题` + "</div><div class=\"highlight\">" + `内容` + "</div>"
    data =     {
       "touser" : "@all",
       "msgtype" : "textcard",//textcard为卡片信息，text为文字信息
       "agentid" : `企业微信botID（e.g.100002）`,
       "textcard" : {
                "title" : "大标题",
                "description" : tmptext,
                "url" : "点击卡片打开的URL",
                "btntxt":"卡片按钮文字"
       },
        "text" : {
                "content" : `内容`
            },//text和textcard二选一即可
       "enable_id_trans": 0,
       "enable_duplicate_check": 1,
       "duplicate_check_interval": 1800
    }
    posturl = QYWXposturl.format(access_token)
    requests.post(posturl, data=json.dumps(data))

```
       "textcard" : {
                "title" : "大标题",
                "description" : tmptext,
                "url" : "点击卡片打开的URL",
                "btntxt":"卡片按钮文字"
       },
        "text" : {
                "content" : `内容`
            },//text和textcard二选一即可
```
以上两段取舍与` "msgtype" : "textcard",//textcard为卡片信息，text为文字信息`相关

---



并且我这里有一份python的企业微信应用推送的模板，我已经将部分需要的变量及内容进行了标注/注释，您看是否有可能一起加入
