### ISSUE TITLE
ERR

### ISSUE THREAD

**Issue by Epxir** [moeshin/cx-auto-sign#36]
<img width="243" alt="image" src="https://user-images.githubusercontent.com/79371047/199400734-7a6c9d92-34f5-4009-b8c0-a8e5f7f2064c.png">
#90 它取消了心跳显示，它这之后还在运行吗？

**Comment by moeshin** [comment]
还在运行，如果下一个 60 秒内还没有心跳，会再打一条日志出来

**Comment by Epxir** [comment]
@moeshin 此时可通过调用相同的通知方式提示，如几分钟仍，推送

**Comment by moeshin** [comment]
511f4eb
