### ISSUE TITLE
获取不到课程信息  签到报错

### ISSUE THREAD

**Issue by q2929843202** [moeshin/cx-auto-sign#4]
获取不到课程  自动签到报错 应该不是ip问题我换个三个网络测
![未命名1641549050](https://user-images.githubusercontent.com/97284858/148526547-372141a5-be9b-45a2-9a9d-96414b6911c7.png)
![未命名1641549257](https://user-images.githubusercontent.com/97284858/148526623-176b300d-cacf-402f-b4b9-c920e244cf59.png)
![1641549792](https://user-images.githubusercontent.com/97284858/148527718-d203928d-857b-4aca-ab9d-b2abd9bbaec1.png)
试

**Comment by moeshin** [comment]
https://github.com/moeshin/cx-auto-sign/actions/runs/1667153177

**Comment by moeshin** [comment]
没问题了吧
