### ISSUE TITLE
v2.1.2无法添加账户

### ISSUE THREAD

**Issue by MoAccelerator** [moeshin/cx-auto-sign#5]
![image](https://user-images.githubusercontent.com/45995147/154874919-5ee8215c-8576-4ad1-8030-291f1432b6d3.png)
在rm -rf上一个版本之后 解压新版本使用init指令初始化，然后报错 The -u field is required.

**Comment by moeshin** [comment]
配置被删了，得重新初始化嘛

**Comment by MoAccelerator** [comment]
不。。其实是我发现导入之前的数据还是提示需要-u添加账户 所以我直接初始化了。。。但是它还是会报错

**Comment by MoAccelerator** [comment]
![image](https://user-images.githubusercontent.com/45995147/154875294-0122d551-0e38-47d4-8be8-88e924f8bc9f.png)
![image](https://user-images.githubusercontent.com/45995147/154875317-a86fa24c-8842-4f3b-8402-40cc0ace1dbf.png)

**Comment by moeshin** [comment]
有个 `AppConfig.json5` 文件，添加或修改 `DefaultUsername` 为你账号

**Comment by MoAccelerator** [comment]
多谢 ！已经成功运行了
