### ISSUE TITLE
挂tmux上status.sh无数据

### ISSUE THREAD

**Issue by Epxir** [moeshin/cx-auto-sign#6]
<img width="389" alt="截屏2022-02-23 上午1 05 24" src="https://user-images.githubusercontent.com/79371047/155181994-193e3cc1-92b0-49bd-ad1f-f57ece57e562.png">

其他情况下没试，感谢一直更新！

**Comment by moeshin** [comment]
这些状态得用 `start.sh` 启动才能看到。
start 是利用 nohup 挂起，日志保存在 Log 文件夹下，进程 id 保存在 Pid 下。
https://github.com/moeshin/cx-auto-sign/blob/383d564382970bf1f9f11e7b1590e62d7402d197/scripts/.base.sh#L50

**Comment by moeshin** [comment]
或者用 'ps.sh' 康康
