### ISSUE TITLE
关于多用户通知的适配

### ISSUE THREAD

**Issue by XYZliang** [moeshin/cx-auto-sign#8]
通知的配置仅受应用配置文件所控制。这导致在多人签到时，所有通知都发送到了这个所配置的地方。
为什么不吧通知配置放在用户配置内达到通知精确到用户呢？

**Comment by moeshin** [comment]
可以单独在 用户配置 中配置

https://github.com/moeshin/cx-auto-sign#%E5%BA%94%E7%94%A8%E9%85%8D%E7%BD%AE
> 通知，可以在 应用配置 和 用户配置 中配置
