### ISSUE TITLE
WebApi无法访问

### ISSUE THREAD

**Issue by XYZliang** [moeshin/cx-auto-sign#9]
相关配置如下：
appsettings.json
`{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndPoints": {
      "Http": {
        "Url": "http://*:5743"
      }
    }
  }
}
`
用户配置文件：
`{
  "Username": "********",
  "Password": "********",
  "Fid": null,
  "WebApi": true,
  "ServerChanKey": "********",
  "Course": {********
  }
}`
启动后控制台有相关启动日志：
<img width="798" alt="image" src="https://user-images.githubusercontent.com/59312540/158110989-bf738f43-4f04-4794-b104-7625e69f3038.png">
浏览器无论是访问http://127.0.0.1:5743/status还是http://localhost:5743/status都无法访问：
<img width="746" alt="image" src="https://user-images.githubusercontent.com/59312540/158111230-8d6bcfae-b4bd-4c7e-a88f-e3fa51197f58.png">

**Comment by moeshin** [comment]
改 appsettings.json 这个没用，默认值被我写死了

https://github.com/moeshin/cx-auto-sign/blob/383d564382970bf1f9f11e7b1590e62d7402d197/cx-auto-sign/WorkCommand.cs#L49-L80

或者直接在用户配置里写规则吧

**Comment by moeshin** [comment]
日志没有被打印出来，你更新看看？

**Comment by XYZliang** [comment]
我试试

**Comment by XYZliang** [comment]
我之前使用的是[Release页面](https://github.com/moeshin/cx-auto-sign/releases)中的版本。使用了Action编译的最新测试版后，api可以正常访问
